# Generated by Django 6.1 on 2026-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='タイトル')),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
                ('updata_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
